### PR TITLE
Fix PasswordTextInput component

### LINKED ISSUE #59: PasswordTextInput doesn't allow font customization
I'm trying to create a login screen using this component, but it has  default font and it doesn't let me customize it. Below is a screenshot with the problem:

Screenshot (Aug 6, 2020 3_06_45 PM)

### PR DESCRIPTION
**Pull request by pedrohperalta**
## Types of changes

- Bug fix

## Description of the proposed changes

This PR fixes #59 by making the inout font the same as the rest of the input. Also, it reduces the hide/show icon size a little bit.

## Screenshot

Simulator Screen Shot - iPhone 11 - 2020-08-06 at 15 42 09

### CODE REVIEW

**Comment by barbosa** [comment]
@pedrohperalta @lenoirzamboni build is broken

**Comment by lenoirzamboni** [comment]
> @pedrohperalta @lenoirzamboni build is broken

@barbosa Can you elaborate more on this? I just run the app here, with these changes and it seems fine.

**Comment by barbosa** [comment]
@lenoirzamboni @pedrohperalta Sorry. What I meant is that this PR broke the build. Tests are failing on master. We need to fix it. I have added a rule to not merge PRs if CI is broken so we prevent this from happening again.

**Comment by lenoirzamboni** [comment]
> @lenoirzamboni @pedrohperalta Sorry. What I meant is that this PR broke the build. Tests are failing on master. We need to fix it. I have added a rule to not merge PRs if CI is broken so we prevent this from happening again.

@barbosa Oh, OK. Good idea!

**Pull request merged**
